drop table MESSAGE;
drop table FRIEND;
drop table MWCHAT_USER;

CREATE TABLE MESSAGE (ID BIGINT NOT NULL AUTO_INCREMENT, CREATEDATE DATE, DLC TIMESTAMP, FROMUSERID BIGINT, MESSAGE VARCHAR(255), OPERATORID BIGINT, TOUSERID BIGINT, PRIMARY KEY (ID));
CREATE TABLE MWCHAT_USER (ID BIGINT NOT NULL AUTO_INCREMENT, CREATEDATE DATE NOT NULL, DISPLAYNAME VARCHAR(255) NOT NULL, DLC TIMESTAMP NOT NULL, EMAILADDRESS VARCHAR(255) UNIQUE, LOGOFILENAME VARCHAR(255), OPERATORID BIGINT NOT NULL, PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE FRIEND (ID BIGINT NOT NULL AUTO_INCREMENT, CREATEDATE DATE, DLC TIMESTAMP, FRIENDID BIGINT, OPERATORID BIGINT, USERID BIGINT, PRIMARY KEY (ID));

insert into MWCHAT_USER (CREATEDATE,DISPLAYNAME,OPERATORID,PASSWORD) values (now(), 'ping li', 1, '123');
