CREATE TABLE MESSAGE (ID BIGINT NOT NULL, OPERATORID BIGINT, CREATEDATE DATE, DLC TIMESTAMP, MESSAGE VARCHAR(255), FROMMWCHATUSERID BIGINT, TOMWCHATUSERID BIGINT, PRIMARY KEY (ID));
CREATE TABLE MWCHAT_USER (ID BIGINT NOT NULL, CREATEDATE DATE, DISPLAYNAME VARCHAR(255) NOT NULL, DLC TIMESTAMP, EMAILADDRESS VARCHAR(255) UNIQUE, LOGOFILENAME VARCHAR(255) NOT NULL, OPERATORID BIGINT, PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE FRIEND (ID BIGINT NOT NULL, CREATEDATE DATE, DLC TIMESTAMP, OPERATORID BIGINT, MWCHATUSERID BIGINT, MWCHATFRIENDID BIGINT, PRIMARY KEY (ID));
ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_TOMWCHATUSERID FOREIGN KEY (TOMWCHATUSERID) REFERENCES MWCHAT_USER (ID);
ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_FROMMWCHATUSERID FOREIGN KEY (FROMMWCHATUSERID) REFERENCES MWCHAT_USER (ID);
ALTER TABLE FRIEND ADD CONSTRAINT FK_FRIEND_MWCHATUSERID FOREIGN KEY (MWCHATUSERID) REFERENCES MWCHAT_USER (ID);
ALTER TABLE FRIEND ADD CONSTRAINT FK_FRIEND_MWCHATFRIENDID FOREIGN KEY (MWCHATFRIENDID) REFERENCES MWCHAT_USER (ID);
