/**
 * This file was generated by the JPA Modeler
 */
package com.etongcoding.mwchat.model;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author pingli
 */
@XmlRootElement
@Entity
@Table(name = "MWCHAT_USER")
public class Mwchatuser {

    @Column(nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @NotNull
    private Long id;

    @Column(name = "DLC", nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.TIMESTAMP)
    @NotNull
    private Date dlc;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    private Long operatorId;

    @Column(nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.DATE)
    @NotNull
    private Date createDate;

    @Column(unique = true)
    @Basic
    private String emailAddress;

    @Column(nullable = false)
    @Basic
    private String displayName;

    @Basic
    private String logoFileName;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    private String password;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDlc() {
        return this.dlc;
    }

    public void setDlc(Date dlc) {
        this.dlc = dlc;
    }

    public Long getOperatorId() {
        return this.operatorId;
    }

    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getLogoFileName() {
        return this.logoFileName;
    }

    public void setLogoFileName(String logoFileName) {
        this.logoFileName = logoFileName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
